### ISSUE TITLE
Parse Nuget Packages

### ISSUE THREAD

**Issue by kamranayub** [bevry/projectz#18]
It's just an XML file. Spec is here:

http://docs.nuget.org/docs/reference/nuspec-reference

This would be useful for Windows devs (me) who use Nuget. You can use Nuget with any type of project, but it's built into Visual Studio so typically Microsoft stack devs use it. For example, we're using it for [eonarheim/Excalibur](/eonarheim/Excalibur).

**Comment by balupton** [comment]
From my understand, nuget is being phased out right?
