### ISSUE TITLE
Literate CoffeeScript is hard to read

### ISSUE THREAD

**Issue by RobLoach** [bevry/projectz#20]
Is it just me, or does Literate CoffeeScript make the code quite unreadable?
https://github.com/bevry/projectz/blob/master/src/lib/projectz.litcoffee

I find it great for small and short scripts, but for big files like projectz.litcoffee, it makes it quite difficult to read since the indentation goes all over the place:
https://raw.github.com/bevry/projectz/master/src/lib/projectz.litcoffee

Thoughts?

**Comment by balupton** [comment]
Perhaps... v1 was rewritten in es6+ so closing

**Comment by balupton** [comment]
v1.0.0 resolves this
