### ISSUE TITLE
Empty line in the beginning of the readme required

### ISSUE THREAD

**Issue by mightyiam** [bevry/projectz#53]
Thank you for this. I love it.

I've noticed that if `<!-- TITLE -->` is at the top of the file, it doesn't get replaced.

**Comment by pflannery** [comment]
It's something to do with [part of the regex](https://github.com/bevry/projectz/blob/master/src/lib/projectz-util.coffee#L55) when replacing entries. It seems to expect a `\n`. 
When adding a blank line at the top of the README it should work

**Comment by balupton** [comment]
v1.0.0 resolves this

**Comment by mightyiam** [comment]
Thank you.
