### ISSUE TITLE
: No such file or directory

### ISSUE THREAD

**Issue by mightyiam** [bevry/projectz#59]
![screenshot from 2015-02-09 18 06 46](https://cloud.githubusercontent.com/assets/635591/6109841/7e3fd734-b086-11e4-8fc4-cf0ba271a8f8.png)

**Comment by pflannery** [comment]
ah I see why, its because the above cmd line ```projectz compile``` would expect projectz to be in your path env. 

Instead it should be executed like [shown here](https://github.com/bevry/projectz#directly)

Example:
```node ./node_modules/projectz/bin/projectz compile``` 

Would be a nice feature to have this setup globally so we can run as ```projectz compile```

**Comment by mightyiam** [comment]
It seems to me that if you provide something in `bin` then people are going to be expecting to be able to run it as an executable, not requiring `node <file>`.

I have it in my paths and I'm probably not the only one, since I don't even know how it got to my env.

**Comment by pflannery** [comment]
when projectz is not installed globally then you would have to run as ```node ./node_modules/bin/projectz compile``` unless you have a special path pointing to ```./node_modules/bin```, (windows users wont have this path by default)

if projectz is installed globally then the bin file is [detected via the bin package entry](https://github.com/bevry/projectz/blob/master/package.json#L76-L78) by npm and copied to npm's path so that ```projectz compile``` would work.

In both of these scenarios I'm not getting a ```no such file or directory``` error and instead it compiles correctly.

1. What happens when you run ```node ./node_modules/bin/projectz compile``` ? does that work?
2. Also does projectz exist in your global npm modules?

**Comment by balupton** [comment]
When using it locally, you can probably shorthand it to:

```
./node_modules/.bin/projectz compile
```

Which uses the executable that npm creates for us.

**Comment by mightyiam** [comment]
Thank you, @pflannery and @balupton. I do not have it globally. I like it local in `devDependencies`.

Running `./node_modules/.bin/projectz compile` also give me `: No such file or directory`.

**Comment by mightyiam** [comment]
This is `v0.4.1`.

**Comment by pflannery** [comment]
whats your os? is it ubuntu?

what happens when you run ```node``` does that error also?

**Comment by mightyiam** [comment]
It is Ubuntu 15.04.

`$ node` gets me into node shell. Otherwise I wouldn't be able to get any work done :smile_cat:

**Comment by RobLoach** [comment]
Confirmed on Ubuntu 14.10...

```
$ ./node_modules/.bin/projectz compile
: No such file or directory
$ node ./node_modules/.bin/projectz compile
info: Initialising project
$ ./node_modules/.bin/projectz --version
: No such file or directory
$ node ./node_modules/.bin/projectz --version
0.4.1
$ npm install projectz -g
$ projectz
: No such file or directory
```

**Comment by pflannery** [comment]
ok I can recreate this on ubuntu 14.04.

when I run ```node ./node_modules/projectz/out/bin/projectz.js compile``` it works. I will keep looking

**Comment by pflannery** [comment]
I think what's happened is that publishing the npm package from my windows box has put crlf's in to all the package files. There is an issue [here](https://github.com/npm/npm/issues/2097)

I dont usually have crlf in any of my projects but they seem to of crept back in some where along the lines.

I'm going to sort my git settings out and submit a patch...I've also noticed an issue when using the ```-d``` option so i will fix that too

**Comment by pflannery** [comment]
Turns out Github for Windows is ignoring my git line ending preferences and using CRLF in every clone I make. Will have to use the terminal to clone from now on :'( (hoping for a fix)

**Comment by pflannery** [comment]
fixed in https://github.com/bevry/projectz/commit/921d628df6aa9472d72e0f304ba88db1bec52d11

@mightyiam please confirm

**Comment by mightyiam** [comment]
Thank you, @pflannery. Confirmed fixed.
