### ISSUE TITLE
Removes newline at end of package.json and bower.json

### ISSUE THREAD

**Issue by hvoecking** [bevry/projectz#60]
After calling `compile` the package.json and bower.json files are missing the newline which is needed for git and vim. Here is an example diff:
```diff
-}
+}
\ No newline at end of file
```

**Comment by balupton** [comment]
Why is it needed for git and vim? Never had an issue before with git.

**Comment by hvoecking** [comment]
It's actually a [unix thing](http://unix.stackexchange.com/a/18789) I just mentioned these tools because that's where for me the newlines are relevant:

- If you open a file in vim and save it (no matter if you modified it or not), it automatically appends a newline (therefore you always have a diff at the end of the file, even if you did not actually change something in the file).
- Git (and github) complain if you remove the newline at the end of the file in a commit as shown above.

**Comment by mightyiam** [comment]
:+1: Vim makes the same newline for me, as well.

This is like [EditorConfig](http://editorconfig.org/)'s `insert_final_newline = true`.

It shouldn't remove a newline, if one exists. It shouldn't add one, as well, FWIW.

**Comment by balupton** [comment]
> It shouldn't remove a newline, if one exists. It shouldn't add one, as well, FWIW.

Good idea. Will see what we can do. @pflannery do you want to grab this one?

**Comment by pflannery** [comment]
@balupton Im guessing this is just a matter of adding a new line during "Save package files" like ```data = JSON.stringify(@dataForPackagesEnhanced[name], null, '  ') + '\n'``` ??

(Shame we cant reference line number to projectz.litcoffee files)

**Comment by pflannery** [comment]
> It shouldn't remove a newline, if one exists. It shouldn't add one, as well, FWIW.

I've determined that both npm and bower (init, --save and --save-dev) append an LF to the file so I don't think its worth the extra effort in trying to detect if an LF wasn't present originally. Instead my PR just does what npm and bower do and that's append an LF to the end of the JSON

**Comment by mightyiam** [comment]
> Instead my PR just does what npm and bower do and that's append an LF to the end of the JSON
Great

**Comment by mightyiam** [comment]
Thank you.
