### ISSUE TITLE
updating to 0.5.0 outputs {#type} in to license

### ISSUE THREAD

**Issue by pflannery** [bevry/projectz#65]
Seems now projectz 0.5.0 will now only allow two license types. 
Previous versions allowed us to put our own preferred license type.

Can we keep it so that we can have custom license types in the README?

**Comment by balupton** [comment]
It [should still allow](https://github.com/bevry/projectz/blob/c9f1070b9abd7926019db0f95e0400719657f386/src/lib/license-util.coffee#L88-L90) custom license types... what is the output you are getting?

**Comment by pflannery** [comment]
at the very bottom of https://github.com/pflannery/chai-v8-optimisation/blob/master/README.md I get {#type}, when I revert back to 0.4.3 it works again.

**Comment by balupton** [comment]
v1.0.0 resolves this

**Comment by pflannery** [comment]
Thanks
