### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by balupton** [bevry/projectz#75]
I've been concerned that the name `projectz` is a bit too confusing to use in dialogue.

I've reserved the name `metabuild` by cross-publishing `projectz` to it.

Let me know if you've ever encountered or not encountered an issue with the name `projectz`

For what it's worth, `projectz` was `readme-utils` [earlier](https://github.com/bevry/projectz/blob/master/HISTORY.md#v002-2013-september-19) before it evolved into a project build tool, of which its name changed to `projectz`, however I've since realised isn't actually a project build tool, but rather just a meta build tool, hence why `metabuild` is on the table, as we could own that problem area with a stronger name for the problem.

**Comment by cherihung** [comment]
i just started using this for one of my projects. really nice. i've not run into problems with the name but would support changing to `metabuild`

**Comment by RobLoach** [comment]
Naw, `metabuild` is way too generic. Way too meta, if you will.... Keep with Projectz. It's good. Helps you manage your projectz.

**Comment by balupton** [comment]
yeah, tbh, I can't really be bothered going through the dramas of changing the name - it does make [presenting this project way more of a tongue twister](https://github.com/elegant-talk/elegant), but whatever

**Comment by RobLoach** [comment]
The projector projects Projectz project.
