### ISSUE TITLE
Use remark

### ISSUE THREAD

**Issue by danielbayley** [bevry/projectz#88]
Related to #85… Why not utilise _[remark](http://remark.js.org)_?

**Comment by balupton** [comment]
Can you provide a link to remark? I haven’t heard of it

**Comment by danielbayley** [comment]
@balupton Link is the name ☝️ 😄

**Comment by balupton** [comment]
ah right, iOctocat doesn't show links then - works fine on normal github! Will check it out.

**Comment by balupton** [comment]
Closing in favour of a comment on #85
