### ISSUE TITLE
Greenkeeper as a contributor

### ISSUE THREAD

**Issue by digitalsadhu** [bevry/projectz#89]
Hey there @balupton, hows it going?

I've noticed that greenkeeper gets automatically included in the contributors list. Is there any way to avoid bots ending up in the contributors list?

**Comment by digitalsadhu** [comment]
Also, some contributors appear multiple times. Appears to be 1x with email and 1x with github user:

```
"contributors": [
    "Richard Walker <digitalsadhu@gmail.com>",
    "Richard Walker (https://github.com/digitalsadhu)",
    "Greenkeeper (http://greenkeeper.io/)"
  ],
```

**Comment by balupton** [comment]
There isn't really a way for it to know that the two users are the same if both entries don't share the same email or url. For DocPad for instance, we have two different contributors but they share the same name. 

You will need to manually merge them, then projectz will be able to figure out they are the same person.

**Comment by balupton** [comment]
The PR for this getting rid of greenkeeper should be done over at https://github.com/bevry/fellow/issues/1
