### ISSUE TITLE
(cli): Nothing shows up if no arguments were provided 

### ISSUE THREAD

**Issue by jamesgeorge007** [bevry/projectz#93]
Nothing seems to happen if `projectz` was supplied without any sort of arguments.

**Comment by jamesgeorge007** [comment]
IMO, it would be good to show up the help text which gives the user a better picture regarding the usage.

**Comment by jamesgeorge007** [comment]
cc @balupton

**Comment by jamesgeorge007** [comment]
I would happily submit a PR :+1:

**Comment by balupton** [comment]
> I would happily submit a PR 👍

+1

If you are also inclined, a rewrite to TypeScript would be so cool.
